name: Build E404 Kernel (Alioth)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Clone KernelSU
        run: |
          rm -rf KernelSU
          git clone --depth=1 https://github.com/tiann/KernelSU.git KernelSU

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            bc bison build-essential flex git curl \
            libssl-dev libelf-dev python3 zip unzip \
            gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

      - name: Clone Neutron Clang
        run: |
          git clone --depth=1 https://github.com/Neutron-Toolchains/clang clang

      - name: Add Toolchain
        run: |
          echo "$GITHUB_WORKSPACE/clang/bin" >> $GITHUB_PATH

      - name: Generate Config
        run: |
          make O=out ARCH=arm64 vendor/alioth_defconfig
          yes "" | make O=out ARCH=arm64 oldconfig

      - name: Show Compiler
        run: |
          clang --version

      - name: Build Kernel
        run: |
          make -j$(nproc) \
            O=out \
            ARCH=arm64 \
            CC=clang \
            LLVM=1 \
            LLVM_IAS=1 \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_COMPAT=arm-linux-gnueabi-

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            out
